global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'milvus'
    static_configs:
      - targets: ['standalone:9091']
    metrics_path: /metrics
  - job_name: 'etcd'
    static_configs:
      - targets: ['etcd:2379']
    metrics_path: /metrics
  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
    metrics_path: /minio/v2/metrics/cluster

# Purpose:
# - Configures Prometheus to scrape metrics from Milvus, etcd, and MinIO.
# - Sets a 15-second scrape interval for near-real-time monitoring.
# - Targets Milvus metrics endpoint (9091), etcd (2379), and MinIO (9000).
# - Ensures comprehensive observability for performance and health.
