
####################################################################
# Define networks for service communication
networks:
  milvus-network:
    name: milvus-network
    internal: true
    driver: bridge
    ipam:
      driver: default
  minio-network:
    name: minio-network
    internal: true
    driver: bridge
    ipam:
      driver: default
  etcd-network:
    name: etcd-network
    internal: true
    driver: bridge
    ipam:
      driver: default
  prometheus-network:
    name: prometheus-network
    internal: true
    driver: bridge
    ipam:
      driver: default
  pulsar-network:
    name: pulsar-network
    internal: true
    driver: bridge
    ipam:
      driver: default
####################################################################
# Define persistent volumes for data durability
volumes:
  grafana_data:
    name: grafana_data
#####################################################################
services:
  ####################################################################
  # Grafana service for visualization
  grafana:
    image: grafana/grafana:8.5.27-ubuntu
    container_name: grafana
    hostname: grafana
    environment:
      # Admin user for Grafana web interface
      GF_SECURITY_ADMIN_USER: admin
      # Admin password for Grafana (replace with a strong, unique password in production)
      GF_SECURITY_ADMIN_PASSWORD: "WW91ckdyYWZhbmFTdHJvbmdQYXNzd29yZDEyMw"
      # Log level for Grafana (info for production, debug for troubleshooting)
      GF_LOG_LEVEL: info
    expose:
      - "3000"
#    ports:
#      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - milvus-network
      - minio-network
      - etcd-network
      - prometheus-network
      - pulsar-network
