{
 "title": "Milvus Docker Cluster",
 "tags": [
  "milvus",
  "docker"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "service", "query": { "query": "label_values(service)" } },
   {
    "name": "instance",
    "query": {
     "query": "label_values(instance, service=~'$service')"
    }
   }
  ]
 },
 "panels": [
  { "title": "Milvus Proxy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Search Vector Count Rate",
   "type": "graph",
   "description": "Per-second rate of searching vectors.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(milvus_proxy_search_vectors_count{service='milvus', instance=~'$instance', environment='milvus-cluster'}[2m])/120) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Insert Vector Count Rate",
   "type": "graph",
   "description": "Per-second rate of inserting vectors.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(milvus_proxy_insert_vectors_count{service='milvus', instance=~'$instance', environment='milvus-cluster'}[2m])/120) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Search Latency",
   "type": "graph",
   "description": "99th percentile and average latency of search requests over the last 2 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, query_type, instance) (rate(milvus_proxy_sq_latency_bucket{service='milvus', instance=~'$instance', environment='milvus-cluster'}[2m])))",
     "legendFormat": "p99-{{query_type}}-{{instance}}"
    },
    {
     "expr": "sum(increase(milvus_proxy_sq_latency_sum{service='milvus', instance=~'$instance', environment='milvus-cluster'}[2m])) by (instance, query_type) / sum(increase(milvus_proxy_sq_latency_count{service='milvus', instance=~'$instance', environment='milvus-cluster'}[2m])) by (instance, query_type)",
     "legendFormat": "avg-{{query_type}}-{{instance}}"
    }
   ]
  },
  { "title": "System Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "etcd Request Rate",
   "type": "graph",
   "description": "etcd server requests per second.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_server_client_requests_total{service='etcd', instance=~'$instance', environment='milvus-cluster'}[2m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MinIO Request Rate",
   "type": "graph",
   "description": "MinIO total requests per second.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(minio_http_requests_total{service='minio', instance=~'$instance', environment='milvus-cluster'}[2m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pulsar Publish Rate",
   "type": "graph",
   "description": "Pulsar message publish rate.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pulsar_producer_msg_rate_in{service='pulsar', instance=~'$instance', environment='milvus-cluster'}[2m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HAProxy Request Rate",
   "type": "graph",
   "description": "HAProxy frontend request rate.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_requests_total{service='haproxy', instance=~'$instance', environment='milvus-cluster'}[2m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Monitoring Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Prometheus Scrape Duration",
   "type": "graph",
   "description": "Prometheus scrape duration.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, instance) (rate(prometheus_tsdb_compaction_duration_seconds_bucket{service='prometheus', instance=~'$instance', environment='milvus-cluster'}[2m])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node CPU Usage",
   "type": "graph",
   "description": "Node Exporter CPU usage.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{service='node_exporter', instance=~'$instance', environment='milvus-cluster', mode!='idle'}[2m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Grafana Request Rate",
   "type": "graph",
   "description": "Grafana request rate.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grafana_request_duration_seconds_count{service='grafana', instance=~'$instance', environment='milvus-cluster'}[2m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "Process CPU usage across services.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{service=~'$service', instance=~'$instance', environment='milvus-cluster'}[5m])",
     "legendFormat": "{{service}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Process memory usage across services.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{service=~'$service', instance=~'$instance', environment='milvus-cluster'}",
     "legendFormat": "{{service}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "description": "Number of goroutines across services.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{service=~'$service', instance=~'$instance', environment='milvus-cluster'}",
     "legendFormat": "{{service}}-{{instance}}"
    }
   ]
  }
 ]
}