{
 "title": "Milvus Cluster Observability",
 "tags": [
  "milvus",
  "monitoring"
 ],
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "job", "label": "Service Job", "query": "label_values(up, job)" }
  ]
 },
 "panels": [
  {
   "title": "Service Availability",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Up" }
   ],
   "targets": [
    {
     "expr": "up{job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Milvus Proxy gRPC Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_server_handling_seconds_sum{job=~\"milvus\", instance=~\".*proxy.*\"}[1m]) / rate(grpc_server_handling_seconds_count{job=~\"milvus\", instance=~\".*proxy.*\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MinIO Object Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "minio_cluster_bucket_objects{job=\"minio\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ETCD Leader Changes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "Changes/min" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_server_leader_changes_seen_total{job=\"etcd\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}