# pg_hba.conf
# This file controls who can connect to the database and how.
# It's like a guest list for our database party.

# TYPE  DATABASE        USER            ADDRESS                 METHOD
# Allow local connections without a password
local   all             all                                     trust

# Allow admin user to connect from any IP with a password
host    all             admin           0.0.0.0/0               scram-sha-256

# Allow replication user to connect from any IP with a password
host    replication     repl            0.0.0.0/0               scram-sha-256